### PR TITLE
Fetching from reddit

### PR DESCRIPTION
**Pull request by LenAnderson**
## work in progress

I started working on properly fetching content from reddit since only gfycat is being fetched at the moment.

Basic fetching for imgur links is already working but needs some testing and further refinement (e.g. using a pure XMLHttpRequest to connect with the imgur API is most likely not the npm way :D).

I am currently using an API key for imgur that I have created myself (for fapinstructor) and store it directly in `fetchImgur.js` which is probably not ideal. I suppose the key should be replaced with one owned by @thefapinstructor and stored in some other location together with other API keys and such...

**Links to hosters:**

- [x] i.imgur.com/id.filetype
- [x] imgur.com/a/id or imgur.com/gallery/id
- [x] imgur.com/id
- [x] i.reddit.com/id.filetype
- [x] 66.media.tumblr.com
- [ ] tumblr.com/post/id
- [ ] wordpress.com or wp.com
- [x] giphy.com
- [ ] gyazo.com
- [ ] other common hosters?
- [ ] what about youtube / vimeo / xhamster / ... (would probably have to be embedded)?

**Other stuff:**

- [ ] detect deleted images (done: reddit, imgur)
- [ ] instead of just the subreddit name, also allow sorting with `/top`, `/new`, ...

### CODE REVIEW

**Comment by thefapinstructor** [comment]
Hey @LenAnderson ,I can generate a key and store it private in travis.  Thanks for taking the time to add the additional functionality!  Please let me know when you are ready for me to merge and we'll sort out the api key issue then.

**Comment by The1nstructor** [comment]
Sorry to bother you, but: 

Are you also planning to do something about the #16 thing?

**Comment by LenAnderson** [comment]
I think that would be out of scope for this PR since you don't really have links to full tumblrs on reddit, only to single posts / images and from what I understand it's querying tumblr's API (getting the list of posts) that's affected by the consent redirects.

I can look into that as well if nobody else is willing to. It's just not very important to me personally as I don't use tumblr and the workaround is so simple.

**Comment by The1nstructor** [comment]
#120 made this work redundant.

**Pull request closed without merging**
