### PR TITLE
Pre-Condition-Bug-Fixing

### PR DESCRIPTION
**Pull request by The1nstructor**
some minor bugs I found and was able to fix!

### CODE REVIEW

**Comment by The1nstructor** [comment]
@thefapinstructor please merge 🔜  😉

**Comment by LenAnderson** [comment]
Regarding https://github.com/fapinstructor/fapinstructor/pull/63/commits/af6d7c41a4eb57c69183cdf6dbec48998cc515cd

Shouldn't it rather say "at least X minutes" (2 < 2.9 < 3)?

**Comment by The1nstructor** [comment]
Ah yeah you are right, forgot that we do not only accept integers there ... 

Thank you! And thank you for reviewing!

**Comment by LenAnderson** [comment]
Great that you added doc comments!

In `handleChange` the  `cast` param is not a type though, it's a function. `Number`, `String`, and `Boolean` are the basic functions provided by JavaScript but we could use more complex, custom conversions as well (e.g. if we wanted to convert `"5..10"` to an array `[5, 6, 7, 8, 9, 10]`).

Maybe something like this?

> a function that converts the input field's value to its intended type

**Pull request merged**
